//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaRap.ExtMainServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtMainServiceClient.IExtMainService")]
    public interface IExtMainService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxHelloWorldInq", ReplyAction="http://tempuri.org/IExtSystemService/TxHelloWorldInqResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTQueryReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMsgReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckStageReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSealMSDReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMailReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLabelLevelInfoReqInParm))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMsgReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.MoTypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSealMSDReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult))]
        AlphaRap.ExtMainServiceClient.CTBaseReqResult TxHelloWorldInq(AlphaRap.ExtMainServiceClient.CTBaseReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxHelloWorldInq", ReplyAction="http://tempuri.org/IExtSystemService/TxHelloWorldInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxHelloWorldInqAsync(AlphaRap.ExtMainServiceClient.CTBaseReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSendMessageInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSendMessageInqResponse")]
        AlphaRap.ExtMainServiceClient.CTSendMsgReqResult TxSendMessageInq(AlphaRap.ExtMainServiceClient.CTSendMsgReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSendMessageInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSendMessageInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSendMsgReqResult> TxSendMessageInqAsync(AlphaRap.ExtMainServiceClient.CTSendMsgReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetProgramByRlcInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetProgramByRlcInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult TxGetProgramByRlcInq(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetProgramByRlcInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetProgramByRlcInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult> TxGetProgramByRlcInqAsync(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoTypeInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoTypeInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult TxGetMoTypeInq(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoTypeInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoTypeInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult> TxGetMoTypeInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoInfoByMbInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoInfoByMbInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult TxGetMoInfoByMbInq(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoInfoByMbInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoInfoByMbInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult> TxGetMoInfoByMbInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxXRayReturnWarehouseAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxXRayReturnWarehouseAltResponse")]
        AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult TxXRayReturnWarehouseAlt(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxXRayReturnWarehouseAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxXRayReturnWarehouseAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult> TxXRayReturnWarehouseAltAsync(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtMapVendorInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtMapVendorInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult TxGetSmtMapVendorInq(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtMapVendorInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtMapVendorInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult> TxGetSmtMapVendorInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetLatestLabelFileInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetLatestLabelFileInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult TxGetLatestLabelFileInq(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetLatestLabelFileInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetLatestLabelFileInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult> TxGetLatestLabelFileInqAsync(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckSfcsStageInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckSfcsStageInqResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMsgReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.MoTypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSealMSDReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult))]
        AlphaRap.ExtMainServiceClient.CTBaseReqResult TxCheckSfcsStageInq(AlphaRap.ExtMainServiceClient.CTCheckStageReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckSfcsStageInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckSfcsStageInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxCheckSfcsStageInqAsync(AlphaRap.ExtMainServiceClient.CTCheckStageReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetWebServiceURLInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetWebServiceURLInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult TxGetWebServiceURLInq(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetWebServiceURLInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetWebServiceURLInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult> TxGetWebServiceURLInqAsync(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtMapNotPcbInputInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtMapNotPcbInputInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtMapNotPcbInputInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtMapNotPcbInputInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtMapNotPcbInputInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtMapNotPcbInputInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtLdMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtLdMapInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtLdMapInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtLdMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtLdMapInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtLdMapInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtLdMap_InlineInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtLdMap_InlineInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtLdMap_InlineInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtLdMap_InlineInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtLdMap_InlineInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtLdMap_InlineInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxChkLdPcbNoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxChkLdPcbNoAltResponse")]
        AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult TxChkLdPcbNoAlt(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxChkLdPcbNoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxChkLdPcbNoAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult> TxChkLdPcbNoAltAsync(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxLdPcbPrintAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxLdPcbPrintAltResponse")]
        AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult TxLdPcbPrintAlt(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxLdPcbPrintAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxLdPcbPrintAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult> TxLdPcbPrintAltAsync(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSMTMapListInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSMTMapListInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult TxGetSMTMapListInq(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSMTMapListInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSMTMapListInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult> TxGetSMTMapListInqAsync(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckPNLabelPNInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckPNLabelPNInqResponse")]
        AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult TxCheckPNLabelPNInq(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckPNLabelPNInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckPNLabelPNInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult> TxCheckPNLabelPNInqAsync(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninIcYrAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninIcYrAltResponse")]
        AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult TxBurninIcYrAlt(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninIcYrAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninIcYrAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult> TxBurninIcYrAltAsync(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCancelPcblotTempAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxCancelPcblotTempAltResponse")]
        AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult TxCancelPcblotTempAlt(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCancelPcblotTempAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxCancelPcblotTempAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult> TxCancelPcblotTempAltAsync(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckSfcsErpPnInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckSfcsErpPnInqResponse")]
        AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult TxCheckSfcsErpPnInq(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckSfcsErpPnInq", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckSfcsErpPnInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult> TxCheckSfcsErpPnInqAsync(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCustSnAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCustSnAltResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult TxGetSmtCustSnAlt(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCustSnAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCustSnAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult> TxGetSmtCustSnAltAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCustSnInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCustSnInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult TxGetSmtCustSnInq(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCustSnInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCustSnInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult> TxGetSmtCustSnInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoSSNInfoInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoSSNInfoInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult TxGetMoSSNInfoInq(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoSSNInfoInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoSSNInfoInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult> TxGetMoSSNInfoInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMBSNMarkInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMBSNMarkInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult TxGetMBSNMarkInq(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMBSNMarkInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMBSNMarkInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult> TxGetMBSNMarkInqAsync(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetBindItemListParentInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetBindItemListParentInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult TxGetBindItemListParentInq(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetBindItemListParentInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetBindItemListParentInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult> TxGetBindItemListParentInqAsync(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninChangeSocketAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninChangeSocketAltResponse")]
        AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult TxBurninChangeSocketAlt(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninChangeSocketAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninChangeSocketAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult> TxBurninChangeSocketAltAsync(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninMaintainHistoryAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninMaintainHistoryAltResponse")]
        AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult TxBurninMaintainHistoryAlt(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxBurninMaintainHistoryAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxBurninMaintainHistoryAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult> TxBurninMaintainHistoryAltAsync(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMbsnBadMarkInq", ReplyAction="http://tempuri.org/IExtSystemService/TxMbsnBadMarkInqResponse")]
        AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult TxMbsnBadMarkInq(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMbsnBadMarkInq", ReplyAction="http://tempuri.org/IExtSystemService/TxMbsnBadMarkInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult> TxMbsnBadMarkInqAsync(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMbsnBadMarkAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxMbsnBadMarkAltResponse")]
        AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult TxMbsnBadMarkAlt(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMbsnBadMarkAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxMbsnBadMarkAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult> TxMbsnBadMarkAltAsync(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtAutoLabelDataAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtAutoLabelDataAltResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult TxGetSmtAutoLabelDataAlt(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtAutoLabelDataAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtAutoLabelDataAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult> TxGetSmtAutoLabelDataAltAsync(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSealMSDAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxSealMSDAltResponse")]
        AlphaRap.ExtMainServiceClient.CTSealMSDReqResult TxSealMSDAlt(AlphaRap.ExtMainServiceClient.CTSealMSDReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSealMSDAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxSealMSDAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSealMSDReqResult> TxSealMSDAltAsync(AlphaRap.ExtMainServiceClient.CTSealMSDReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCbInfoInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCbInfoInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult TxGetSmtCbInfoInq(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetSmtCbInfoInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetSmtCbInfoInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult> TxGetSmtCbInfoInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSmtCsnCombineAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxSmtCsnCombineAltResponse")]
        AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult TxSmtCsnCombineAlt(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSmtCsnCombineAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxSmtCsnCombineAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult> TxSmtCsnCombineAltAsync(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckAtpGlueStatusInfoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckAtpGlueStatusInfoAltResponse")]
        AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult TxCheckAtpGlueStatusInfoAlt(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqInParm parm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxCheckAtpGlueStatusInfoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxCheckAtpGlueStatusInfoAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult> TxCheckAtpGlueStatusInfoAltAsync(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqInParm parm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSTWaferMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSTWaferMapInqResponse")]
        AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult TxSTWaferMapInq(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSTWaferMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSTWaferMapInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult> TxSTWaferMapInqAsync(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetWisRecipeInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetWisRecipeInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult TxGetWisRecipeInq(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetWisRecipeInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetWisRecipeInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult> TxGetWisRecipeInqAsync(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMaintainEapDeployStatusAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxMaintainEapDeployStatusAltResponse")]
        AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult TxMaintainEapDeployStatusAlt(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxMaintainEapDeployStatusAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxMaintainEapDeployStatusAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult> TxMaintainEapDeployStatusAltAsync(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetEapDeploySettingInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetEapDeploySettingInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult TxGetEapDeploySettingInq(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetEapDeploySettingInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetEapDeploySettingInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult> TxGetEapDeploySettingInqAsync(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetAtpLdMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetAtpLdMapInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult TxGetAtpLdMapInq(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetAtpLdMapInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetAtpLdMapInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult> TxGetAtpLdMapInqAsync(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetLabelEFormInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetLabelEFormInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult TxGetLabelEFormInq(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetLabelEFormInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetLabelEFormInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult> TxGetLabelEFormInqAsync(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSendMailInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSendMailInqResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMsgReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.MoTypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSealMSDReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult))]
        AlphaRap.ExtMainServiceClient.CTBaseReqResult TxSendMailInq(AlphaRap.ExtMainServiceClient.CTSendMailReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxSendMailInq", ReplyAction="http://tempuri.org/IExtSystemService/TxSendMailInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxSendMailInqAsync(AlphaRap.ExtMainServiceClient.CTSendMailReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoListByDateInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoListByDateInqResponse")]
        AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult TxGetMoListByDateInq(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxGetMoListByDateInq", ReplyAction="http://tempuri.org/IExtSystemService/TxGetMoListByDateInqResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult> TxGetMoListByDateInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxLabelLevelInfoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxLabelLevelInfoAltResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSendMsgReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.MoTypeInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSealMSDReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult))]
        AlphaRap.ExtMainServiceClient.CTBaseReqResult TxLabelLevelInfoAlt(AlphaRap.ExtMainServiceClient.CTLabelLevelInfoReqInParm req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExtSystemService/TxLabelLevelInfoAlt", ReplyAction="http://tempuri.org/IExtSystemService/TxLabelLevelInfoAltResponse")]
        System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxLabelLevelInfoAltAsync(AlphaRap.ExtMainServiceClient.CTLabelLevelInfoReqInParm req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExtMainServiceChannel : AlphaRap.ExtMainServiceClient.IExtMainService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExtMainServiceClient : System.ServiceModel.ClientBase<AlphaRap.ExtMainServiceClient.IExtMainService>, AlphaRap.ExtMainServiceClient.IExtMainService {
        
        public ExtMainServiceClient() {
        }
        
        public ExtMainServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExtMainServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtMainServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExtMainServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AlphaRap.ExtMainServiceClient.CTBaseReqResult TxHelloWorldInq(AlphaRap.ExtMainServiceClient.CTBaseReqInParm req) {
            return base.Channel.TxHelloWorldInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxHelloWorldInqAsync(AlphaRap.ExtMainServiceClient.CTBaseReqInParm req) {
            return base.Channel.TxHelloWorldInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTSendMsgReqResult TxSendMessageInq(AlphaRap.ExtMainServiceClient.CTSendMsgReqInParm req) {
            return base.Channel.TxSendMessageInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSendMsgReqResult> TxSendMessageInqAsync(AlphaRap.ExtMainServiceClient.CTSendMsgReqInParm req) {
            return base.Channel.TxSendMessageInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult TxGetProgramByRlcInq(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqInParm req) {
            return base.Channel.TxGetProgramByRlcInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqResult> TxGetProgramByRlcInqAsync(AlphaRap.ExtMainServiceClient.CTGetProgramByRlcReqInParm req) {
            return base.Channel.TxGetProgramByRlcInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult TxGetMoTypeInq(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqInParm req) {
            return base.Channel.TxGetMoTypeInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoTypeReqResult> TxGetMoTypeInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoTypeReqInParm req) {
            return base.Channel.TxGetMoTypeInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult TxGetMoInfoByMbInq(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqInParm req) {
            return base.Channel.TxGetMoInfoByMbInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqResult> TxGetMoInfoByMbInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoInfoByMbReqInParm req) {
            return base.Channel.TxGetMoInfoByMbInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult TxXRayReturnWarehouseAlt(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqInParm req) {
            return base.Channel.TxXRayReturnWarehouseAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqResult> TxXRayReturnWarehouseAltAsync(AlphaRap.ExtMainServiceClient.CTRayReturnWarehouseReqInParm req) {
            return base.Channel.TxXRayReturnWarehouseAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult TxGetSmtMapVendorInq(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqInParm req) {
            return base.Channel.TxGetSmtMapVendorInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqResult> TxGetSmtMapVendorInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtMapVendorReqInParm req) {
            return base.Channel.TxGetSmtMapVendorInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult TxGetLatestLabelFileInq(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqInParm req) {
            return base.Channel.TxGetLatestLabelFileInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqResult> TxGetLatestLabelFileInqAsync(AlphaRap.ExtMainServiceClient.CTGetLatestLabelFileReqInParm req) {
            return base.Channel.TxGetLatestLabelFileInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBaseReqResult TxCheckSfcsStageInq(AlphaRap.ExtMainServiceClient.CTCheckStageReqInParm req) {
            return base.Channel.TxCheckSfcsStageInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxCheckSfcsStageInqAsync(AlphaRap.ExtMainServiceClient.CTCheckStageReqInParm req) {
            return base.Channel.TxCheckSfcsStageInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult TxGetWebServiceURLInq(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqInParm req) {
            return base.Channel.TxGetWebServiceURLInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqResult> TxGetWebServiceURLInqAsync(AlphaRap.ExtMainServiceClient.CTGetWebServiceURLReqInParm req) {
            return base.Channel.TxGetWebServiceURLInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtMapNotPcbInputInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtMapNotPcbInputInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtMapNotPcbInputInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtMapNotPcbInputInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtLdMapInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtLdMapInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtLdMapInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtLdMapInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult TxGetSmtLdMap_InlineInq(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtLdMap_InlineInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqResult> TxGetSmtLdMap_InlineInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtLdMapReqInParm req) {
            return base.Channel.TxGetSmtLdMap_InlineInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult TxChkLdPcbNoAlt(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqInParm req) {
            return base.Channel.TxChkLdPcbNoAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqResult> TxChkLdPcbNoAltAsync(AlphaRap.ExtMainServiceClient.CTChkLdPcbNoReqInParm req) {
            return base.Channel.TxChkLdPcbNoAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult TxLdPcbPrintAlt(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqInParm req) {
            return base.Channel.TxLdPcbPrintAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqResult> TxLdPcbPrintAltAsync(AlphaRap.ExtMainServiceClient.CTLdPcbPrintReqInParm req) {
            return base.Channel.TxLdPcbPrintAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult TxGetSMTMapListInq(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqInParm req) {
            return base.Channel.TxGetSMTMapListInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqResult> TxGetSMTMapListInqAsync(AlphaRap.ExtMainServiceClient.CTGetSMTMapListReqInParm req) {
            return base.Channel.TxGetSMTMapListInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult TxCheckPNLabelPNInq(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqInParm req) {
            return base.Channel.TxCheckPNLabelPNInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqResult> TxCheckPNLabelPNInqAsync(AlphaRap.ExtMainServiceClient.CTCheckPNLabelPNReqInParm req) {
            return base.Channel.TxCheckPNLabelPNInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult TxBurninIcYrAlt(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqInParm req) {
            return base.Channel.TxBurninIcYrAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninIcYrReqResult> TxBurninIcYrAltAsync(AlphaRap.ExtMainServiceClient.CTBurninIcYrReqInParm req) {
            return base.Channel.TxBurninIcYrAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult TxCancelPcblotTempAlt(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqInParm req) {
            return base.Channel.TxCancelPcblotTempAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqResult> TxCancelPcblotTempAltAsync(AlphaRap.ExtMainServiceClient.CTCancelPcblotTempReqInParm req) {
            return base.Channel.TxCancelPcblotTempAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult TxCheckSfcsErpPnInq(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqInParm req) {
            return base.Channel.TxCheckSfcsErpPnInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqResult> TxCheckSfcsErpPnInqAsync(AlphaRap.ExtMainServiceClient.CTCheckSfcsErpPnReqInParm req) {
            return base.Channel.TxCheckSfcsErpPnInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult TxGetSmtCustSnAlt(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req) {
            return base.Channel.TxGetSmtCustSnAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult> TxGetSmtCustSnAltAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req) {
            return base.Channel.TxGetSmtCustSnAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult TxGetSmtCustSnInq(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req) {
            return base.Channel.TxGetSmtCustSnInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqResult> TxGetSmtCustSnInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCustSnReqInParm req) {
            return base.Channel.TxGetSmtCustSnInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult TxGetMoSSNInfoInq(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqInParm req) {
            return base.Channel.TxGetMoSSNInfoInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqResult> TxGetMoSSNInfoInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoSSNInfoReqInParm req) {
            return base.Channel.TxGetMoSSNInfoInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult TxGetMBSNMarkInq(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqInParm req) {
            return base.Channel.TxGetMBSNMarkInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqResult> TxGetMBSNMarkInqAsync(AlphaRap.ExtMainServiceClient.CTGetMBSNMarkReqInParm req) {
            return base.Channel.TxGetMBSNMarkInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult TxGetBindItemListParentInq(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqInParm req) {
            return base.Channel.TxGetBindItemListParentInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqResult> TxGetBindItemListParentInqAsync(AlphaRap.ExtMainServiceClient.CTGetBindItemListParentReqInParm req) {
            return base.Channel.TxGetBindItemListParentInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult TxBurninChangeSocketAlt(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqInParm req) {
            return base.Channel.TxBurninChangeSocketAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqResult> TxBurninChangeSocketAltAsync(AlphaRap.ExtMainServiceClient.CTBurninChangeSocketReqInParm req) {
            return base.Channel.TxBurninChangeSocketAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult TxBurninMaintainHistoryAlt(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqInParm req) {
            return base.Channel.TxBurninMaintainHistoryAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqResult> TxBurninMaintainHistoryAltAsync(AlphaRap.ExtMainServiceClient.CTBurninMaintainHistoryReqInParm req) {
            return base.Channel.TxBurninMaintainHistoryAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult TxMbsnBadMarkInq(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqInParm req) {
            return base.Channel.TxMbsnBadMarkInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqResult> TxMbsnBadMarkInqAsync(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkInqReqInParm req) {
            return base.Channel.TxMbsnBadMarkInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult TxMbsnBadMarkAlt(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqInParm req) {
            return base.Channel.TxMbsnBadMarkAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqResult> TxMbsnBadMarkAltAsync(AlphaRap.ExtMainServiceClient.CTMbsnBadMarkAltReqInParm req) {
            return base.Channel.TxMbsnBadMarkAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult TxGetSmtAutoLabelDataAlt(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqInParm req) {
            return base.Channel.TxGetSmtAutoLabelDataAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqResult> TxGetSmtAutoLabelDataAltAsync(AlphaRap.ExtMainServiceClient.CTGetSmtAutoLabelDataReqInParm req) {
            return base.Channel.TxGetSmtAutoLabelDataAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTSealMSDReqResult TxSealMSDAlt(AlphaRap.ExtMainServiceClient.CTSealMSDReqInParm req) {
            return base.Channel.TxSealMSDAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSealMSDReqResult> TxSealMSDAltAsync(AlphaRap.ExtMainServiceClient.CTSealMSDReqInParm req) {
            return base.Channel.TxSealMSDAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult TxGetSmtCbInfoInq(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqInParm req) {
            return base.Channel.TxGetSmtCbInfoInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqResult> TxGetSmtCbInfoInqAsync(AlphaRap.ExtMainServiceClient.CTGetSmtCbInfoReqInParm req) {
            return base.Channel.TxGetSmtCbInfoInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult TxSmtCsnCombineAlt(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqInParm req) {
            return base.Channel.TxSmtCsnCombineAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqResult> TxSmtCsnCombineAltAsync(AlphaRap.ExtMainServiceClient.CTSmtCsnCombineReqInParm req) {
            return base.Channel.TxSmtCsnCombineAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult TxCheckAtpGlueStatusInfoAlt(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqInParm parm) {
            return base.Channel.TxCheckAtpGlueStatusInfoAlt(parm);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqResult> TxCheckAtpGlueStatusInfoAltAsync(AlphaRap.ExtMainServiceClient.CTCheckAtpGlueStatusInfoReqInParm parm) {
            return base.Channel.TxCheckAtpGlueStatusInfoAltAsync(parm);
        }
        
        public AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult TxSTWaferMapInq(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqInParm req) {
            return base.Channel.TxSTWaferMapInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTSTWaferMapReqResult> TxSTWaferMapInqAsync(AlphaRap.ExtMainServiceClient.CTSTWaferMapReqInParm req) {
            return base.Channel.TxSTWaferMapInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult TxGetWisRecipeInq(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqInParm req) {
            return base.Channel.TxGetWisRecipeInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqResult> TxGetWisRecipeInqAsync(AlphaRap.ExtMainServiceClient.CTGetWisRecipeReqInParm req) {
            return base.Channel.TxGetWisRecipeInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult TxMaintainEapDeployStatusAlt(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqInParm req) {
            return base.Channel.TxMaintainEapDeployStatusAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqResult> TxMaintainEapDeployStatusAltAsync(AlphaRap.ExtMainServiceClient.CTMaintainEapDeployStatusReqInParm req) {
            return base.Channel.TxMaintainEapDeployStatusAltAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult TxGetEapDeploySettingInq(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqInParm req) {
            return base.Channel.TxGetEapDeploySettingInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqResult> TxGetEapDeploySettingInqAsync(AlphaRap.ExtMainServiceClient.CTGetEapDeploySettingReqInParm req) {
            return base.Channel.TxGetEapDeploySettingInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult TxGetAtpLdMapInq(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqInParm req) {
            return base.Channel.TxGetAtpLdMapInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqResult> TxGetAtpLdMapInqAsync(AlphaRap.ExtMainServiceClient.CTGetAtpLdMapReqInParm req) {
            return base.Channel.TxGetAtpLdMapInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult TxGetLabelEFormInq(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqInParm req) {
            return base.Channel.TxGetLabelEFormInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqResult> TxGetLabelEFormInqAsync(AlphaRap.ExtMainServiceClient.CTGetLabelEFormReqInParm req) {
            return base.Channel.TxGetLabelEFormInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBaseReqResult TxSendMailInq(AlphaRap.ExtMainServiceClient.CTSendMailReqInParm req) {
            return base.Channel.TxSendMailInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxSendMailInqAsync(AlphaRap.ExtMainServiceClient.CTSendMailReqInParm req) {
            return base.Channel.TxSendMailInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult TxGetMoListByDateInq(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqInParm req) {
            return base.Channel.TxGetMoListByDateInq(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqResult> TxGetMoListByDateInqAsync(AlphaRap.ExtMainServiceClient.CTGetMoListByDateReqInParm req) {
            return base.Channel.TxGetMoListByDateInqAsync(req);
        }
        
        public AlphaRap.ExtMainServiceClient.CTBaseReqResult TxLabelLevelInfoAlt(AlphaRap.ExtMainServiceClient.CTLabelLevelInfoReqInParm req) {
            return base.Channel.TxLabelLevelInfoAlt(req);
        }
        
        public System.Threading.Tasks.Task<AlphaRap.ExtMainServiceClient.CTBaseReqResult> TxLabelLevelInfoAltAsync(AlphaRap.ExtMainServiceClient.CTLabelLevelInfoReqInParm req) {
            return base.Channel.TxLabelLevelInfoAltAsync(req);
        }
    }
}
